pet:LocationOffset(-1, 0, 0)
pet:ResponseTime(0.4)
pet:LifeTime(1)
pet:CollisionRadius(0.3)
pet:DistanceMax(8)
pet:FollowTurnTime(0.4)
pet:SetSpeedRatio(1)
pet:CanFly(false)
pet:LevelSize(3, 1.35, 1.35, 1.35)
pet:LevelSize(4, 1.44, 1.44, 1.44)
pet:LevelMaterial(3, 0)
pet:LevelMaterial(4, 0)
pet:LevelMaterial(4, 1)
pet:LevelTexture(3, 0, "/mesh/character/thirdperson/avatar/indie/pet/dog01/Tex_dog01a_trinket_c.dds")
pet:LevelTexture(4, 0, "/mesh/character/thirdperson/avatar/indie/pet/dog01/Tex_dog01b_trinket_c.dds")
pet:LevelTexture(4, 1, "/mesh/character/thirdperson/avatar/indie/pet/dog01/Tex_dog01b_trinket_c.dds")
pet:SetVerticalHeight(0)
pet:SetSingleVerticalHeight(0.5)
