pet:LocationOffset(-1, 1, 0)
pet:ResponseTime(0.3)
pet:LifeTime(1)
pet:CollisionRadius(0.3)
pet:DistanceMax(8)
pet:FollowTurnTime(0.3)
pet:SetSpeedRatio(1)
pet:LevelSize(3, 1.3, 1.3, 1.3)
pet:LevelSize(4, 1.5, 1.5, 1.5)
pet:LevelMaterial(3, 0)
pet:LevelMaterial(4, 0)
pet:LevelMaterial(4, 1)
pet:LevelTexture(3, 0, "/mesh/character/thirdperson/avatar/indie/pet/dragon02/Tex_dragon02a_trinket_c.dds")
pet:LevelTexture(4, 0, "/mesh/character/thirdperson/avatar/indie/pet/dragon02/Tex_dragon02b_trinket_c.dds")
pet:LevelTexture(4, 1, "/mesh/character/thirdperson/avatar/indie/pet/dragon02/Tex_dragon02b_trinket_c.dds")
