pet:LocationOffset(-1, 1, 0)
pet:ResponseTime(0.4)
pet:LifeTime(1)
pet:CollisionRadius(0.3)
pet:DistanceMax(8)
pet:FollowTurnTime(0.4)
pet:SetSpeedRatio(1)
pet:LevelSize(3, 1.5, 1.5, 1.5)
pet:LevelSize(4, 1.7, 1.7, 1.7)
pet:LevelMaterial(3, 0)
pet:LevelMaterial(4, 0)
pet:LevelMaterial(4, 1)
pet:LevelTexture(3, 0, "/mesh/character/thirdperson/avatar/indie/pet/dragon06/Tex_dragon06a_trinket_c.dds")
pet:LevelTexture(4, 0, "/mesh/character/thirdperson/avatar/indie/pet/dragon06/Tex_dragon06b_trinket_c.dds")
pet:LevelTexture(4, 1, "/mesh/character/thirdperson/avatar/indie/pet/dragon06/Tex_dragon06b_trinket_c.dds")
