pet:LocationOffset(-1, 1, 0)
pet:ResponseTime(0.4)
pet:LifeTime(1)
pet:CollisionRadius(0.3)
pet:DistanceMax(8)
pet:FollowTurnTime(0.4)
pet:SetSpeedRatio(1)
pet:LevelSize(3, 1.35, 1.35, 1.35)
pet:LevelSize(4, 1.44, 1.44, 1.44)
pet:LevelMaterial(3, 0)
pet:LevelMaterial(3, 1)
pet:LevelMaterial(4, 0)
pet:LevelMaterial(4, 2)
pet:LevelTexture(3, 0, "/mesh/character/thirdperson/avatar/indie/pet/dragon08/Tex_dragon08a_trinket_d.dds")
pet:LevelTexture(3, 1, "/mesh/character/thirdperson/avatar/indie/pet/dragon08/Tex_dragon08a_trinket_d.dds")
pet:LevelTexture(4, 0, "/mesh/character/thirdperson/avatar/indie/pet/dragon08/Tex_dragon08b_trinket_d.dds")
pet:LevelTexture(4, 2, "/mesh/character/thirdperson/avatar/indie/pet/dragon08/Tex_dragon08b_trinket_d.dds")
