pet:LocationOffset(-1, 1, 0)
pet:ResponseTime(0.3)
pet:LifeTime(1)
pet:CollisionRadius(0.3)
pet:DistanceMax(8)
pet:FollowTurnTime(0.3)
pet:SetSpeedRatio(1)
pet:LevelSize(0, 1, 1, 1)
pet:LevelSize(1, 0.6, 0.6, 0.6)
pet:LevelSize(2, 0.75, 0.75, 0.75)
pet:LevelSize(3, 0.9, 0.9, 0.9)
pet:LevelSize(4, 1.1, 1.1, 1.1)
pet:LevelMaterial(0, 0)
pet:LevelMaterial(1, 0)
pet:LevelMaterial(1, 1)
pet:LevelMaterial(2, 0)
pet:LevelMaterial(2, 1)
pet:LevelMaterial(3, 0)
pet:LevelMaterial(3, 1)
pet:LevelMaterial(4, 0)
pet:LevelMaterial(4, 2)
pet:LevelTexture(0, 0, "/mesh/character/thirdperson/avatar/indie/pet/monster/Tex_monster01a_trinket_c.dds")
pet:LevelTexture(1, 0, "/mesh/character/thirdperson/avatar/indie/pet/monster/Tex_monster01b_trinket_c.dds")
pet:LevelTexture(1, 1, "/mesh/character/thirdperson/avatar/indie/pet/monster/Tex_monster01b_trinket_c.dds")
pet:LevelTexture(2, 0, "/mesh/character/thirdperson/avatar/indie/pet/monster/Tex_monster01c_trinket_c.dds")
pet:LevelTexture(2, 1, "/mesh/character/thirdperson/avatar/indie/pet/monster/Tex_monster01c_trinket_c.dds")
pet:LevelTexture(3, 0, "/mesh/character/thirdperson/avatar/indie/pet/monster/Tex_monster01d_trinket_c.dds")
pet:LevelTexture(3, 1, "/mesh/character/thirdperson/avatar/indie/pet/monster/Tex_monster01d_trinket_c.dds")
pet:LevelTexture(4, 0, "/mesh/character/thirdperson/avatar/indie/pet/monster/Tex_monster01e_trinket_c.dds")
pet:LevelTexture(4, 2, "/mesh/character/thirdperson/avatar/indie/pet/monster/Tex_monster01e_trinket_c.dds")
