weapon:SetMesh("rvl", "shield_47/rvl1_lod0.mesh")
weapon:SetMesh("rvr", "shield_47/rvr1_lod0.mesh")
weapon.skeleton = "/skeleton/shield_47.skel"
weapon.animation_set = "shield_47"
weapon.trail_particle = "shield_trail"
weapon.shield_trail_particle = "shield_glow"
weapon.sound_name = "shield"
weapon.icon = texture("/ui/skinF/lobby/shield_47.tga")
weapon.ammo_icon = texture("/ui/skinF/lobby/shield_47.tga")
weapon.cross_hair_icon = texture("/ui/weapon/knives.dds")
weapon.fire_time1 = 0.7
weapon.fire_time2 = 0.7
weapon.fire_time3 = 0.7
weapon.delay_time1 = 0.66
weapon.delay_time2 = 0.23
weapon.delay_time3 = 0.13
weapon.pause_time1 = 0.2
weapon.pause_time2 = 0.2
weapon.pause_time3 = 0.2
weapon.shield_trail_particle_time = 0.07
weapon.size = Vector3(0.45, 0.63, 0.05)
weapon.size1 = Vector3(0.8, 0.7, 0.05)
weapon.local_position = Vector3(0.07, 0.015, 0.15)
weapon.local_position1 = Vector3(0.07, 0, 0.15)
weapon.attach_particle = "q_shield2"
weapon.shield_attach_particle = "q_shield"
weapon.shoot_animation1 = "shoot1"
weapon.shoot_animation2 = "shoot2"
weapon.shoot_animation3 = "shoot3"
