module("Mode_Introduce", package.seeall)
contents = {
  {
    {
      1,
      "jike",
      "tips_abilities_Paradise_talking01"
    },
    {
      1,
      "jike",
      "tips_abilities_Paradise_talking02"
    },
    {
      1,
      "jike",
      "tips_abilities_Paradise_talking03"
    },
    {
      2,
      "langli",
      "tips_abilities_Paradise_talking04"
    },
    {
      2,
      "langli",
      "tips_abilities_Paradise_talking05"
    },
    {
      1,
      "jike",
      "tips_abilities_Paradise_talking06"
    },
    {
      2,
      "langli",
      "tips_abilities_Paradise_talking07"
    },
    {
      1,
      "jike",
      "tips_abilities_Paradise_talking08"
    },
    {
      1,
      "jike",
      "tips_abilities_Paradise_talking09"
    },
    {
      1,
      "jike",
      "tips_abilities_Paradise_talking10"
    },
    {
      1,
      "jike",
      "tips_abilities_Paradise_talking11"
    },
    {
      1,
      "jike",
      "tips_abilities_Paradise_talking12"
    },
    {
      1,
      "jike",
      "tips_abilities_Paradise_talking13"
    },
    {
      1,
      "jike",
      "tips_abilities_Paradise_talking14"
    },
    {
      1,
      "jike",
      "tips_abilities_Paradise_talking15"
    },
    {
      1,
      "jike",
      "tips_abilities_Paradise_talking16"
    },
    {
      1,
      "jike",
      "tips_abilities_Paradise_talking17"
    },
    {
      1,
      "jike",
      "tips_abilities_Paradise_talking18"
    },
    {
      1,
      "jike",
      "tips_abilities_Paradise_talking19"
    },
    {
      1,
      "jike",
      "tips_abilities_Paradise_talking20"
    },
    {
      1,
      "jike",
      "tips_abilities_Paradise_talking21"
    },
    {
      1,
      "jike",
      "tips_abilities_Paradise_talking22"
    },
    {
      1,
      "jike",
      "tips_abilities_Paradise_talking23"
    },
    {
      2,
      "langli",
      "tips_abilities_Paradise_talking24"
    },
    {
      2,
      "langli",
      "tips_abilities_Paradise_talking25"
    },
    {
      2,
      "langli",
      "tips_abilities_Paradise_talking26"
    },
    {
      2,
      "langli",
      "tips_abilities_Paradise_talking27"
    },
    {
      2,
      "langli",
      "tips_abilities_Paradise_talking28"
    },
    {
      2,
      "langli",
      "tips_abilities_Paradise_talking29"
    },
    {
      2,
      "langli",
      "tips_abilities_Paradise_talking30"
    },
    {
      2,
      "langli",
      "tips_abilities_Paradise_talking31"
    },
    {
      2,
      "langli",
      "tips_abilities_Paradise_talking32"
    },
    {
      2,
      "langli",
      "tips_abilities_Paradise_talking33"
    },
    {
      2,
      "langli",
      "tips_abilities_Paradise_talking34"
    },
    {
      2,
      "langli",
      "tips_abilities_Paradise_talking35"
    },
    {
      2,
      "langli",
      "tips_abilities_Paradise_talking36"
    },
    {
      2,
      "langli",
      "tips_abilities_Paradise_talking37"
    },
    {
      2,
      "langli",
      "tips_abilities_Paradise_talking38"
    },
    {
      1,
      "jike",
      "tips_abilities_Paradise_talking39"
    },
    {
      1,
      "jike",
      "tips_abilities_Paradise_talking40"
    },
    {
      1,
      "jiangshiyf",
      "tips_abilities_Paradise_talking41"
    },
    {
      1,
      "jike",
      "tips_abilities_Paradise_talking42"
    },
    {
      1,
      "jike",
      "tips_abilities_Paradise_talking43"
    },
    {
      2,
      "jiangshikg",
      "tips_abilities_Paradise_talking44"
    },
    {
      1,
      "jike",
      "tips_abilities_Paradise_talking45"
    },
    {
      1,
      "jike",
      "tips_abilities_Paradise_talking46"
    },
    {
      2,
      "jiangshiyuanding",
      "tips_abilities_Paradise_talking47"
    },
    {
      1,
      "jike",
      "tips_abilities_Paradise_talking48"
    },
    {
      1,
      "jiangshishouling",
      "tips_abilities_Paradise_talking49"
    },
    {
      1,
      "jike",
      "tips_abilities_Paradise_talking50"
    },
    {
      2,
      "langli",
      "tips_abilities_Paradise_talking51"
    },
    {
      1,
      "jike",
      "tips_abilities_Paradise_talking52"
    }
  },
  {
    {
      1,
      "langren",
      "UI_abilities_langren_story01"
    },
    {
      1,
      "langren",
      "UI_abilities_langren_story02"
    },
    {
      1,
      "langren",
      "UI_abilities_langren_story03"
    },
    {
      1,
      "langren",
      "UI_abilities_langren_story04"
    },
    {
      1,
      "langren",
      "UI_abilities_langren_story05"
    },
    {
      1,
      "langren",
      "UI_abilities_langren_story06"
    },
    {
      1,
      "langren",
      "UI_abilities_langren_story07"
    },
    {
      1,
      "langren",
      "UI_abilities_langren_story08"
    },
    {
      1,
      "red_langren",
      "UI_abilities_langren_story09"
    },
    {
      2,
      "blue_langren",
      "UI_abilities_langren_story10",
      x = 355
    },
    {
      1,
      "langren",
      "UI_abilities_langren_story11"
    },
    {
      1,
      "langren",
      "UI_abilities_langren_story12"
    },
    {
      1,
      "langren",
      "UI_abilities_langren_story13"
    },
    {
      1,
      "langren",
      "UI_abilities_langren_story14"
    },
    {
      1,
      "langren",
      "UI_abilities_langren_story15"
    },
    {
      1,
      "langren",
      "UI_abilities_langren_story16"
    },
    {
      1,
      "langren",
      "UI_abilities_langren_story17"
    }
  }
}
hero_card_info = {
  {
    {
      avatarId = "100153",
      resource = "langli",
      describe = "UI_common_langli_jieshao"
    },
    {
      avatarId = "100154",
      resource = "jike",
      describe = "UI_common_jike_jieshao"
    }
  },
  {
    {
      avatarId = "100173",
      resource = "langren",
      describe = "UI_common_langwang_jieshao"
    }
  }
}
