weapon:SetMesh("rv", "grenadelauncherbullet_31/rv1_lod0.mesh", 0)
weapon.ik_enable = false
weapon.hand_bind_type = "kHandNone"
weapon.name = "ÊÖÀ×"
weapon.sound_name = "grenade"
weapon.skeleton = "/skeleton/grenadelauncher_01.skel"
weapon.icon = texture("/ui/skinF/lobby/grenade_31.tga")
weapon.kill_icon = texture("/ui/weapon/grenade_01.dds")
weapon.ammo_icon = texture("/ui/ingameF/weapon_ammo_icon/grenade_31.tga")
weapon.cross_hair_icon = texture("/ui/weapon/grenade.dds")
weapon.explode_particle = "s_bow_explosion"
weapon.explode_sound = "go/impact_3d/explosion_grenlauncher"
weapon.throw_sound_3d = "go/weapons_3d/grenade/fire"
weapon.sound_name = "grenade"
weapon.explode_particle = "grenade_explosion"
weapon.explode_particle_has_buff = "grenadelauncher_effect_mephitis"
